/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UplinkRouteImport } from './routes/uplink'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusRouteImport } from './routes/status'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UplinkLifetimeRouteImport } from './routes/uplink_.lifetime'
import { Route as UUsernameRouteImport } from './routes/u.$username'

const UplinkRoute = UplinkRouteImport.update({
  id: '/uplink',
  path: '/uplink',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UplinkLifetimeRoute = UplinkLifetimeRouteImport.update({
  id: '/uplink_/lifetime',
  path: '/uplink/lifetime',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/business': typeof BusinessRoute
  '/callback': typeof CallbackRoute
  '/channels': typeof ChannelsRoute
  '/download': typeof DownloadRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/uplink': typeof UplinkRoute
  '/u/$username': typeof UUsernameRoute
  '/uplink/lifetime': typeof UplinkLifetimeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/business': typeof BusinessRoute
  '/callback': typeof CallbackRoute
  '/channels': typeof ChannelsRoute
  '/download': typeof DownloadRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/uplink': typeof UplinkRoute
  '/u/$username': typeof UUsernameRoute
  '/uplink/lifetime': typeof UplinkLifetimeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/business': typeof BusinessRoute
  '/callback': typeof CallbackRoute
  '/channels': typeof ChannelsRoute
  '/download': typeof DownloadRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/uplink': typeof UplinkRoute
  '/u/$username': typeof UUsernameRoute
  '/uplink_/lifetime': typeof UplinkLifetimeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/architecture'
    | '/business'
    | '/callback'
    | '/channels'
    | '/download'
    | '/invite'
    | '/legal'
    | '/status'
    | '/support'
    | '/uplink'
    | '/u/$username'
    | '/uplink/lifetime'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/architecture'
    | '/business'
    | '/callback'
    | '/channels'
    | '/download'
    | '/invite'
    | '/legal'
    | '/status'
    | '/support'
    | '/uplink'
    | '/u/$username'
    | '/uplink/lifetime'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/architecture'
    | '/business'
    | '/callback'
    | '/channels'
    | '/download'
    | '/invite'
    | '/legal'
    | '/status'
    | '/support'
    | '/uplink'
    | '/u/$username'
    | '/uplink_/lifetime'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ArchitectureRoute: typeof ArchitectureRoute
  BusinessRoute: typeof BusinessRoute
  CallbackRoute: typeof CallbackRoute
  ChannelsRoute: typeof ChannelsRoute
  DownloadRoute: typeof DownloadRoute
  InviteRoute: typeof InviteRoute
  LegalRoute: typeof LegalRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  UplinkRoute: typeof UplinkRoute
  UUsernameRoute: typeof UUsernameRoute
  UplinkLifetimeRoute: typeof UplinkLifetimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uplink': {
      id: '/uplink'
      path: '/uplink'
      fullPath: '/uplink'
      preLoaderRoute: typeof UplinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uplink_/lifetime': {
      id: '/uplink_/lifetime'
      path: '/uplink/lifetime'
      fullPath: '/uplink/lifetime'
      preLoaderRoute: typeof UplinkLifetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ArchitectureRoute: ArchitectureRoute,
  BusinessRoute: BusinessRoute,
  CallbackRoute: CallbackRoute,
  ChannelsRoute: ChannelsRoute,
  DownloadRoute: DownloadRoute,
  InviteRoute: InviteRoute,
  LegalRoute: LegalRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  UplinkRoute: UplinkRoute,
  UUsernameRoute: UUsernameRoute,
  UplinkLifetimeRoute: UplinkLifetimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
