/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as UplinkRouteImport } from './routes/uplink'
import { Route as TssSpaShellRouteImport } from './routes/tss-spa-shell'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as FantasyRouteImport } from './routes/fantasy'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as ChannelsRouteImport } from './routes/channels'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UplinkLifetimeRouteImport } from './routes/uplink_.lifetime'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as DownloadOsRouteImport } from './routes/download_.$os'
import { Route as AdminVersionsRouteImport } from './routes/admin.versions'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdminsRouteImport } from './routes/admin.admins'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const UplinkRoute = UplinkRouteImport.update({
  id: '/uplink',
  path: '/uplink',
  getParentRoute: () => rootRouteImport,
} as any)
const TssSpaShellRoute = TssSpaShellRouteImport.update({
  id: '/tss-spa-shell',
  path: '/tss-spa-shell',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const FantasyRoute = FantasyRouteImport.update({
  id: '/fantasy',
  path: '/fantasy',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRoute = ChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UplinkLifetimeRoute = UplinkLifetimeRouteImport.update({
  id: '/uplink_/lifetime',
  path: '/uplink/lifetime',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadOsRoute = DownloadOsRouteImport.update({
  id: '/download_/$os',
  path: '/download/$os',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVersionsRoute = AdminVersionsRouteImport.update({
  id: '/versions',
  path: '/versions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/business': typeof BusinessRoute
  '/callback': typeof CallbackRoute
  '/channels': typeof ChannelsRoute
  '/download': typeof DownloadRoute
  '/fantasy': typeof FantasyRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/releases': typeof ReleasesRoute
  '/sports': typeof SportsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/tss-spa-shell': typeof TssSpaShellRoute
  '/uplink': typeof UplinkRoute
  '/widgets': typeof WidgetsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/download/$os': typeof DownloadOsRoute
  '/u/$username': typeof UUsernameRoute
  '/uplink/lifetime': typeof UplinkLifetimeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/architecture': typeof ArchitectureRoute
  '/business': typeof BusinessRoute
  '/callback': typeof CallbackRoute
  '/channels': typeof ChannelsRoute
  '/download': typeof DownloadRoute
  '/fantasy': typeof FantasyRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/releases': typeof ReleasesRoute
  '/sports': typeof SportsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/tss-spa-shell': typeof TssSpaShellRoute
  '/uplink': typeof UplinkRoute
  '/widgets': typeof WidgetsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/download/$os': typeof DownloadOsRoute
  '/u/$username': typeof UUsernameRoute
  '/uplink/lifetime': typeof UplinkLifetimeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/architecture': typeof ArchitectureRoute
  '/business': typeof BusinessRoute
  '/callback': typeof CallbackRoute
  '/channels': typeof ChannelsRoute
  '/download': typeof DownloadRoute
  '/fantasy': typeof FantasyRoute
  '/invite': typeof InviteRoute
  '/legal': typeof LegalRoute
  '/markets': typeof MarketsRoute
  '/news': typeof NewsRoute
  '/releases': typeof ReleasesRoute
  '/sports': typeof SportsRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/tss-spa-shell': typeof TssSpaShellRoute
  '/uplink': typeof UplinkRoute
  '/widgets': typeof WidgetsRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/versions': typeof AdminVersionsRoute
  '/download_/$os': typeof DownloadOsRoute
  '/u/$username': typeof UUsernameRoute
  '/uplink_/lifetime': typeof UplinkLifetimeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/architecture'
    | '/business'
    | '/callback'
    | '/channels'
    | '/download'
    | '/fantasy'
    | '/invite'
    | '/legal'
    | '/markets'
    | '/news'
    | '/releases'
    | '/sports'
    | '/status'
    | '/support'
    | '/tss-spa-shell'
    | '/uplink'
    | '/widgets'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/versions'
    | '/download/$os'
    | '/u/$username'
    | '/uplink/lifetime'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/architecture'
    | '/business'
    | '/callback'
    | '/channels'
    | '/download'
    | '/fantasy'
    | '/invite'
    | '/legal'
    | '/markets'
    | '/news'
    | '/releases'
    | '/sports'
    | '/status'
    | '/support'
    | '/tss-spa-shell'
    | '/uplink'
    | '/widgets'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/versions'
    | '/download/$os'
    | '/u/$username'
    | '/uplink/lifetime'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/architecture'
    | '/business'
    | '/callback'
    | '/channels'
    | '/download'
    | '/fantasy'
    | '/invite'
    | '/legal'
    | '/markets'
    | '/news'
    | '/releases'
    | '/sports'
    | '/status'
    | '/support'
    | '/tss-spa-shell'
    | '/uplink'
    | '/widgets'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/versions'
    | '/download_/$os'
    | '/u/$username'
    | '/uplink_/lifetime'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArchitectureRoute: typeof ArchitectureRoute
  BusinessRoute: typeof BusinessRoute
  CallbackRoute: typeof CallbackRoute
  ChannelsRoute: typeof ChannelsRoute
  DownloadRoute: typeof DownloadRoute
  FantasyRoute: typeof FantasyRoute
  InviteRoute: typeof InviteRoute
  LegalRoute: typeof LegalRoute
  MarketsRoute: typeof MarketsRoute
  NewsRoute: typeof NewsRoute
  ReleasesRoute: typeof ReleasesRoute
  SportsRoute: typeof SportsRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  TssSpaShellRoute: typeof TssSpaShellRoute
  UplinkRoute: typeof UplinkRoute
  WidgetsRoute: typeof WidgetsRoute
  DownloadOsRoute: typeof DownloadOsRoute
  UUsernameRoute: typeof UUsernameRoute
  UplinkLifetimeRoute: typeof UplinkLifetimeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uplink': {
      id: '/uplink'
      path: '/uplink'
      fullPath: '/uplink'
      preLoaderRoute: typeof UplinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tss-spa-shell': {
      id: '/tss-spa-shell'
      path: '/tss-spa-shell'
      fullPath: '/tss-spa-shell'
      preLoaderRoute: typeof TssSpaShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fantasy': {
      id: '/fantasy'
      path: '/fantasy'
      fullPath: '/fantasy'
      preLoaderRoute: typeof FantasyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/uplink_/lifetime': {
      id: '/uplink_/lifetime'
      path: '/uplink/lifetime'
      fullPath: '/uplink/lifetime'
      preLoaderRoute: typeof UplinkLifetimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download_/$os': {
      id: '/download_/$os'
      path: '/download/$os'
      fullPath: '/download/$os'
      preLoaderRoute: typeof DownloadOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/versions': {
      id: '/admin/versions'
      path: '/versions'
      fullPath: '/admin/versions'
      preLoaderRoute: typeof AdminVersionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVersionsRoute: typeof AdminVersionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVersionsRoute: AdminVersionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ArchitectureRoute: ArchitectureRoute,
  BusinessRoute: BusinessRoute,
  CallbackRoute: CallbackRoute,
  ChannelsRoute: ChannelsRoute,
  DownloadRoute: DownloadRoute,
  FantasyRoute: FantasyRoute,
  InviteRoute: InviteRoute,
  LegalRoute: LegalRoute,
  MarketsRoute: MarketsRoute,
  NewsRoute: NewsRoute,
  ReleasesRoute: ReleasesRoute,
  SportsRoute: SportsRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  TssSpaShellRoute: TssSpaShellRoute,
  UplinkRoute: UplinkRoute,
  WidgetsRoute: WidgetsRoute,
  DownloadOsRoute: DownloadOsRoute,
  UUsernameRoute: UUsernameRoute,
  UplinkLifetimeRoute: UplinkLifetimeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
