-- Scrollr schema baseline.
--
-- Squashed from the 38 migrations that previously lived in six separate
-- directories across five services (api/, channels/fantasy/api/, and the
-- finance/sports/rss/predictions Rust services). core-api is now the single
-- owner of every shared table (VISION 4.3); the ingesters are pure writers
-- and run no migrations.
--
-- Generated by applying that retired chain to an empty database and dumping
-- the result, so it is exactly the schema that chain produced -- with one
-- deliberate change: user_channels -> user_widgets and channel_type ->
-- widget_type (VISION 4.4). Scrollr has no users, so this is a straight
-- rename with no compatibility seam.
--
-- Write new migrations on top of this file; do not edit it.
-- business_leads (TABLE)

CREATE TABLE business_leads (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    name text NOT NULL,
    email text NOT NULL,
    company text NOT NULL,
    use_case text NOT NULL,
    message text NOT NULL,
    ip_redacted text,
    user_agent text,
    notified_at timestamp with time zone,
    auto_replied_at timestamp with time zone,
    replied_at timestamp with time zone
);

CREATE SEQUENCE business_leads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE business_leads_id_seq OWNED BY business_leads.id;

-- games (TABLE)

CREATE TABLE games (
    id integer NOT NULL,
    league character varying(50) NOT NULL,
    sport character varying(50) DEFAULT ''::character varying NOT NULL,
    external_game_id character varying(100) NOT NULL,
    link character varying(500),
    home_team_name character varying(100) NOT NULL,
    home_team_logo character varying(500),
    home_team_score integer,
    away_team_name character varying(100) NOT NULL,
    away_team_logo character varying(500),
    away_team_score integer,
    start_time timestamp with time zone NOT NULL,
    short_detail character varying(200),
    state character varying(50) NOT NULL,
    status_short character varying(20),
    status_long character varying(100),
    timer character varying(20),
    venue character varying(200),
    season character varying(20),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    home_team_code character varying(10),
    away_team_code character varying(10)
);

CREATE SEQUENCE games_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE games_id_seq OWNED BY games.id;

-- markets (TABLE)

CREATE TABLE markets (
    id text NOT NULL,
    source text DEFAULT 'kalshi'::text NOT NULL,
    ticker text NOT NULL,
    event_ticker text,
    series_ticker text,
    category text,
    title text,
    subtitle text,
    yes_price integer,
    yes_bid integer,
    yes_ask integer,
    prev_yes_price integer,
    volume bigint,
    volume_24h bigint,
    open_interest bigint,
    status text,
    result text,
    is_primary boolean DEFAULT true NOT NULL,
    open_time timestamp with time zone,
    close_time timestamp with time zone,
    link text,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    event_title text DEFAULT ''::text NOT NULL,
    event_rank smallint DEFAULT 1 NOT NULL,
    in_sweep boolean DEFAULT true NOT NULL,
    settled_at timestamp with time zone
);

ALTER TABLE ONLY markets REPLICA IDENTITY FULL;

-- osticket_message_ids (TABLE)

CREATE TABLE osticket_message_ids (
    id bigint NOT NULL,
    ticket_number text NOT NULL,
    message_id text NOT NULL,
    recipient_email text NOT NULL,
    direction text NOT NULL,
    captured_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT osticket_message_ids_direction_check CHECK ((direction = ANY (ARRAY['outbound_osticket'::text, 'outbound_ai'::text, 'outbound_partner_notification'::text, 'inbound_user'::text, 'unknown'::text])))
);

CREATE SEQUENCE osticket_message_ids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE osticket_message_ids_id_seq OWNED BY osticket_message_ids.id;

-- rss_items (TABLE)

CREATE TABLE rss_items (
    id integer NOT NULL,
    feed_url text NOT NULL,
    guid text NOT NULL,
    title text NOT NULL,
    link text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    source_name text DEFAULT ''::text NOT NULL,
    published_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE rss_items_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE rss_items_id_seq OWNED BY rss_items.id;

-- standings (TABLE)

CREATE TABLE standings (
    id integer NOT NULL,
    league character varying(50) NOT NULL,
    team_name character varying(100) NOT NULL,
    team_code character varying(10),
    team_logo character varying(500),
    rank integer,
    wins integer DEFAULT 0 NOT NULL,
    losses integer DEFAULT 0 NOT NULL,
    draws integer DEFAULT 0 NOT NULL,
    points integer,
    games_played integer DEFAULT 0 NOT NULL,
    goal_diff integer,
    description character varying(200),
    form character varying(20),
    group_name character varying(100),
    season character varying(20),
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    sport_api character varying(50),
    pct character varying(10),
    games_behind character varying(10),
    otl integer,
    goals_for integer,
    goals_against integer,
    points_for integer,
    points_against integer,
    streak character varying(10)
);

ALTER TABLE ONLY standings REPLICA IDENTITY FULL;

CREATE SEQUENCE standings_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE standings_id_seq OWNED BY standings.id;

-- stripe_customers (TABLE)

CREATE TABLE stripe_customers (
    logto_sub text NOT NULL,
    stripe_customer_id text NOT NULL,
    stripe_subscription_id text,
    plan text DEFAULT 'free'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    current_period_end timestamp with time zone,
    lifetime boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- stripe_webhook_events (TABLE)

CREATE TABLE stripe_webhook_events (
    event_id text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- support_drafts (TABLE)

CREATE TABLE support_drafts (
    id bigint NOT NULL,
    ticket_number text NOT NULL,
    user_email text NOT NULL,
    user_name text,
    original_subject text NOT NULL,
    draft_body_html text NOT NULL,
    ai_summary text,
    ai_category text,
    ai_priority text,
    ai_channel text,
    ai_duplicate_of text,
    ai_confidence text,
    status text NOT NULL,
    edited_body_html text,
    decided_at timestamp with time zone,
    sent_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    osticket_thread_entry_id bigint,
    should_close boolean DEFAULT false NOT NULL,
    user_message_html text,
    CONSTRAINT support_drafts_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'edited'::text, 'skipped'::text, 'sent'::text, 'failed'::text])))
);

CREATE SEQUENCE support_drafts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE support_drafts_id_seq OWNED BY support_drafts.id;

-- support_ticket_threads (TABLE)

CREATE TABLE support_ticket_threads (
    ticket_number text NOT NULL,
    discord_thread_id text NOT NULL,
    channel_id text NOT NULL,
    archived boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- teams (TABLE)

CREATE TABLE teams (
    id integer NOT NULL,
    league character varying(50) NOT NULL,
    external_id integer NOT NULL,
    name character varying(100) NOT NULL,
    code character varying(10),
    logo character varying(500),
    country character varying(100),
    season character varying(20),
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ONLY teams REPLICA IDENTITY FULL;

CREATE SEQUENCE teams_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE teams_id_seq OWNED BY teams.id;

-- tracked_feeds (TABLE)

CREATE TABLE tracked_feeds (
    url text NOT NULL,
    name text NOT NULL,
    category text DEFAULT 'General'::text NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    consecutive_failures integer DEFAULT 0 NOT NULL,
    last_error text,
    last_error_at timestamp with time zone,
    last_success_at timestamp with time zone,
    added_by text,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- tracked_leagues (TABLE)

CREATE TABLE tracked_leagues (
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    sport_api character varying(50) DEFAULT ''::character varying NOT NULL,
    api_host character varying(200) DEFAULT ''::character varying NOT NULL,
    league_id integer DEFAULT 0 NOT NULL,
    category character varying(50) DEFAULT 'Other'::character varying NOT NULL,
    country character varying(100),
    logo_url character varying(500),
    season character varying(20),
    season_format character varying(20),
    offseason_months integer[],
    is_enabled boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    last_polled_at timestamp with time zone,
    last_poll_success_at timestamp with time zone,
    last_poll_error text
);

CREATE SEQUENCE tracked_leagues_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE tracked_leagues_id_seq OWNED BY tracked_leagues.id;

-- tracked_markets (TABLE)

CREATE TABLE tracked_markets (
    id integer NOT NULL,
    ticker text NOT NULL,
    title text,
    category text,
    series_ticker text,
    is_enabled boolean DEFAULT true,
    last_polled_at timestamp with time zone,
    last_poll_success_at timestamp with time zone,
    last_poll_error text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE SEQUENCE tracked_markets_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE tracked_markets_id_seq OWNED BY tracked_markets.id;

-- tracked_symbols (TABLE)

CREATE TABLE tracked_symbols (
    id integer NOT NULL,
    symbol character varying(30) NOT NULL,
    is_enabled boolean DEFAULT true,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    name character varying(100),
    category character varying(50),
    exchange character varying(20),
    link character varying(255)
);

CREATE SEQUENCE tracked_symbols_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE tracked_symbols_id_seq OWNED BY tracked_symbols.id;

-- trades (TABLE)

CREATE TABLE trades (
    id integer NOT NULL,
    symbol character varying(30) NOT NULL,
    price numeric(10,2) DEFAULT 0 NOT NULL,
    previous_close numeric(10,2) DEFAULT 0 NOT NULL,
    price_change numeric(10,2) DEFAULT 0 NOT NULL,
    percentage_change numeric(5,2) DEFAULT 0 NOT NULL,
    direction character varying(10) DEFAULT 'flat'::character varying NOT NULL,
    last_updated timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

CREATE SEQUENCE trades_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE trades_id_seq OWNED BY trades.id;

-- user_widgets (TABLE)

CREATE TABLE user_widgets (
    id integer NOT NULL,
    logto_sub text NOT NULL,
    widget_type text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    visible boolean DEFAULT true NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE SEQUENCE user_channels_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE user_channels_id_seq OWNED BY user_widgets.id;

-- user_custom_feeds (TABLE)

CREATE TABLE user_custom_feeds (
    logto_sub text NOT NULL,
    url text NOT NULL,
    name text NOT NULL,
    category text DEFAULT 'Custom'::text NOT NULL,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- user_deletion_requests (TABLE)

CREATE TABLE user_deletion_requests (
    logto_sub text NOT NULL,
    requested_at timestamp with time zone DEFAULT now() NOT NULL,
    purge_at timestamp with time zone NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    canceled_at timestamp with time zone,
    purged_at timestamp with time zone
);

-- user_preferences (TABLE)

CREATE TABLE user_preferences (
    logto_sub text NOT NULL,
    feed_mode text DEFAULT 'comfort'::text NOT NULL,
    feed_position text DEFAULT 'bottom'::text NOT NULL,
    feed_behavior text DEFAULT 'overlay'::text NOT NULL,
    feed_enabled boolean DEFAULT true NOT NULL,
    enabled_sites jsonb DEFAULT '[]'::jsonb NOT NULL,
    disabled_sites jsonb DEFAULT '[]'::jsonb NOT NULL,
    subscription_tier text DEFAULT 'free'::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);

-- yahoo_leagues (TABLE)

CREATE TABLE yahoo_leagues (
    league_key character varying(50) NOT NULL,
    name character varying(255) NOT NULL,
    game_code character varying(10) NOT NULL,
    season character varying(10) NOT NULL,
    data jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- yahoo_matchups (TABLE)

CREATE TABLE yahoo_matchups (
    league_key character varying(50) NOT NULL,
    week smallint NOT NULL,
    data jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- yahoo_rosters (TABLE)

CREATE TABLE yahoo_rosters (
    team_key character varying(50) NOT NULL,
    league_key character varying(50) NOT NULL,
    data jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- yahoo_standings (TABLE)

CREATE TABLE yahoo_standings (
    league_key character varying(50) NOT NULL,
    data jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- yahoo_user_leagues (TABLE)

CREATE TABLE yahoo_user_leagues (
    guid character varying(100) NOT NULL,
    league_key character varying(50) NOT NULL,
    team_key character varying(50),
    team_name character varying(255),
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- yahoo_users (TABLE)

CREATE TABLE yahoo_users (
    guid character varying(100) NOT NULL,
    logto_sub character varying(255),
    refresh_token text NOT NULL,
    last_sync timestamp with time zone,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ONLY business_leads ALTER COLUMN id SET DEFAULT nextval('business_leads_id_seq'::regclass);

ALTER TABLE ONLY games ALTER COLUMN id SET DEFAULT nextval('games_id_seq'::regclass);

ALTER TABLE ONLY osticket_message_ids ALTER COLUMN id SET DEFAULT nextval('osticket_message_ids_id_seq'::regclass);

ALTER TABLE ONLY rss_items ALTER COLUMN id SET DEFAULT nextval('rss_items_id_seq'::regclass);

ALTER TABLE ONLY standings ALTER COLUMN id SET DEFAULT nextval('standings_id_seq'::regclass);

ALTER TABLE ONLY support_drafts ALTER COLUMN id SET DEFAULT nextval('support_drafts_id_seq'::regclass);

ALTER TABLE ONLY teams ALTER COLUMN id SET DEFAULT nextval('teams_id_seq'::regclass);

ALTER TABLE ONLY tracked_leagues ALTER COLUMN id SET DEFAULT nextval('tracked_leagues_id_seq'::regclass);

ALTER TABLE ONLY tracked_markets ALTER COLUMN id SET DEFAULT nextval('tracked_markets_id_seq'::regclass);

ALTER TABLE ONLY tracked_symbols ALTER COLUMN id SET DEFAULT nextval('tracked_symbols_id_seq'::regclass);

ALTER TABLE ONLY trades ALTER COLUMN id SET DEFAULT nextval('trades_id_seq'::regclass);

ALTER TABLE ONLY user_widgets ALTER COLUMN id SET DEFAULT nextval('user_channels_id_seq'::regclass);

-- business_leads business_leads_pkey (CONSTRAINT)

ALTER TABLE ONLY business_leads
    ADD CONSTRAINT business_leads_pkey PRIMARY KEY (id);

-- games games_league_external_game_id_key (CONSTRAINT)

ALTER TABLE ONLY games
    ADD CONSTRAINT games_league_external_game_id_key UNIQUE (league, external_game_id);

-- games games_pkey (CONSTRAINT)

ALTER TABLE ONLY games
    ADD CONSTRAINT games_pkey PRIMARY KEY (id);

-- markets markets_pkey (CONSTRAINT)

ALTER TABLE ONLY markets
    ADD CONSTRAINT markets_pkey PRIMARY KEY (id);

-- osticket_message_ids osticket_message_ids_message_id_key (CONSTRAINT)

ALTER TABLE ONLY osticket_message_ids
    ADD CONSTRAINT osticket_message_ids_message_id_key UNIQUE (message_id);

-- osticket_message_ids osticket_message_ids_pkey (CONSTRAINT)

ALTER TABLE ONLY osticket_message_ids
    ADD CONSTRAINT osticket_message_ids_pkey PRIMARY KEY (id);

-- rss_items rss_items_feed_url_guid_key (CONSTRAINT)

ALTER TABLE ONLY rss_items
    ADD CONSTRAINT rss_items_feed_url_guid_key UNIQUE (feed_url, guid);

-- rss_items rss_items_pkey (CONSTRAINT)

ALTER TABLE ONLY rss_items
    ADD CONSTRAINT rss_items_pkey PRIMARY KEY (id);

-- standings standings_league_team_name_season_key (CONSTRAINT)

ALTER TABLE ONLY standings
    ADD CONSTRAINT standings_league_team_name_season_key UNIQUE (league, team_name, season);

-- standings standings_pkey (CONSTRAINT)

ALTER TABLE ONLY standings
    ADD CONSTRAINT standings_pkey PRIMARY KEY (id);

-- stripe_customers stripe_customers_pkey (CONSTRAINT)

ALTER TABLE ONLY stripe_customers
    ADD CONSTRAINT stripe_customers_pkey PRIMARY KEY (logto_sub);

-- stripe_customers stripe_customers_stripe_customer_id_key (CONSTRAINT)

ALTER TABLE ONLY stripe_customers
    ADD CONSTRAINT stripe_customers_stripe_customer_id_key UNIQUE (stripe_customer_id);

-- stripe_webhook_events stripe_webhook_events_pkey (CONSTRAINT)

ALTER TABLE ONLY stripe_webhook_events
    ADD CONSTRAINT stripe_webhook_events_pkey PRIMARY KEY (event_id);

-- support_drafts support_drafts_pkey (CONSTRAINT)

ALTER TABLE ONLY support_drafts
    ADD CONSTRAINT support_drafts_pkey PRIMARY KEY (id);

-- support_ticket_threads support_ticket_threads_pkey (CONSTRAINT)

ALTER TABLE ONLY support_ticket_threads
    ADD CONSTRAINT support_ticket_threads_pkey PRIMARY KEY (ticket_number);

-- teams teams_league_external_id_season_key (CONSTRAINT)

ALTER TABLE ONLY teams
    ADD CONSTRAINT teams_league_external_id_season_key UNIQUE (league, external_id, season);

-- teams teams_pkey (CONSTRAINT)

ALTER TABLE ONLY teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);

-- tracked_feeds tracked_feeds_pkey (CONSTRAINT)

ALTER TABLE ONLY tracked_feeds
    ADD CONSTRAINT tracked_feeds_pkey PRIMARY KEY (url);

-- tracked_leagues tracked_leagues_name_key (CONSTRAINT)

ALTER TABLE ONLY tracked_leagues
    ADD CONSTRAINT tracked_leagues_name_key UNIQUE (name);

-- tracked_leagues tracked_leagues_pkey (CONSTRAINT)

ALTER TABLE ONLY tracked_leagues
    ADD CONSTRAINT tracked_leagues_pkey PRIMARY KEY (id);

-- tracked_markets tracked_markets_pkey (CONSTRAINT)

ALTER TABLE ONLY tracked_markets
    ADD CONSTRAINT tracked_markets_pkey PRIMARY KEY (id);

-- tracked_markets tracked_markets_ticker_key (CONSTRAINT)

ALTER TABLE ONLY tracked_markets
    ADD CONSTRAINT tracked_markets_ticker_key UNIQUE (ticker);

-- tracked_symbols tracked_symbols_pkey (CONSTRAINT)

ALTER TABLE ONLY tracked_symbols
    ADD CONSTRAINT tracked_symbols_pkey PRIMARY KEY (id);

-- tracked_symbols tracked_symbols_symbol_key (CONSTRAINT)

ALTER TABLE ONLY tracked_symbols
    ADD CONSTRAINT tracked_symbols_symbol_key UNIQUE (symbol);

-- trades trades_pkey (CONSTRAINT)

ALTER TABLE ONLY trades
    ADD CONSTRAINT trades_pkey PRIMARY KEY (id);

-- trades trades_symbol_key (CONSTRAINT)

ALTER TABLE ONLY trades
    ADD CONSTRAINT trades_symbol_key UNIQUE (symbol);

-- user_widgets user_channels_logto_sub_channel_type_key (CONSTRAINT)

ALTER TABLE ONLY user_widgets
    ADD CONSTRAINT user_channels_logto_sub_channel_type_key UNIQUE (logto_sub, widget_type);

-- user_widgets user_channels_pkey (CONSTRAINT)

ALTER TABLE ONLY user_widgets
    ADD CONSTRAINT user_channels_pkey PRIMARY KEY (id);

-- user_custom_feeds user_custom_feeds_pkey (CONSTRAINT)

ALTER TABLE ONLY user_custom_feeds
    ADD CONSTRAINT user_custom_feeds_pkey PRIMARY KEY (logto_sub, url);

-- user_deletion_requests user_deletion_requests_pkey (CONSTRAINT)

ALTER TABLE ONLY user_deletion_requests
    ADD CONSTRAINT user_deletion_requests_pkey PRIMARY KEY (logto_sub);

-- user_preferences user_preferences_pkey (CONSTRAINT)

ALTER TABLE ONLY user_preferences
    ADD CONSTRAINT user_preferences_pkey PRIMARY KEY (logto_sub);

-- yahoo_leagues yahoo_leagues_pkey (CONSTRAINT)

ALTER TABLE ONLY yahoo_leagues
    ADD CONSTRAINT yahoo_leagues_pkey PRIMARY KEY (league_key);

-- yahoo_matchups yahoo_matchups_pkey (CONSTRAINT)

ALTER TABLE ONLY yahoo_matchups
    ADD CONSTRAINT yahoo_matchups_pkey PRIMARY KEY (league_key, week);

-- yahoo_rosters yahoo_rosters_pkey (CONSTRAINT)

ALTER TABLE ONLY yahoo_rosters
    ADD CONSTRAINT yahoo_rosters_pkey PRIMARY KEY (team_key);

-- yahoo_standings yahoo_standings_pkey (CONSTRAINT)

ALTER TABLE ONLY yahoo_standings
    ADD CONSTRAINT yahoo_standings_pkey PRIMARY KEY (league_key);

-- yahoo_user_leagues yahoo_user_leagues_pkey (CONSTRAINT)

ALTER TABLE ONLY yahoo_user_leagues
    ADD CONSTRAINT yahoo_user_leagues_pkey PRIMARY KEY (guid, league_key);

-- yahoo_users yahoo_users_logto_sub_key (CONSTRAINT)

ALTER TABLE ONLY yahoo_users
    ADD CONSTRAINT yahoo_users_logto_sub_key UNIQUE (logto_sub);

-- yahoo_users yahoo_users_pkey (CONSTRAINT)

ALTER TABLE ONLY yahoo_users
    ADD CONSTRAINT yahoo_users_pkey PRIMARY KEY (guid);

-- business_leads_created_at_idx (INDEX)

CREATE INDEX business_leads_created_at_idx ON business_leads USING btree (created_at DESC);

-- business_leads_email_idx (INDEX)

CREATE INDEX business_leads_email_idx ON business_leads USING btree (email);

-- idx_osticket_msgids_ticket (INDEX)

CREATE INDEX idx_osticket_msgids_ticket ON osticket_message_ids USING btree (ticket_number);

-- idx_rss_items_published_at (INDEX)

CREATE INDEX idx_rss_items_published_at ON rss_items USING btree (published_at DESC NULLS LAST);

-- idx_stripe_customers_lifetime_false (INDEX)

CREATE INDEX idx_stripe_customers_lifetime_false ON stripe_customers USING btree (logto_sub) WHERE (lifetime = false);

-- idx_support_drafts_status (INDEX)

CREATE INDEX idx_support_drafts_status ON support_drafts USING btree (status);

-- idx_support_drafts_ticket (INDEX)

CREATE INDEX idx_support_drafts_ticket ON support_drafts USING btree (ticket_number);

-- idx_user_custom_feeds_logto_sub (INDEX)

CREATE INDEX idx_user_custom_feeds_logto_sub ON user_custom_feeds USING btree (logto_sub);

-- idx_user_custom_feeds_url (INDEX)

CREATE INDEX idx_user_custom_feeds_url ON user_custom_feeds USING btree (url);

-- idx_webhook_events_created_at (INDEX)

CREATE INDEX idx_webhook_events_created_at ON stripe_webhook_events USING btree (created_at);

-- idx_yahoo_matchups_league_key_week (INDEX)

CREATE INDEX idx_yahoo_matchups_league_key_week ON yahoo_matchups USING btree (league_key, week DESC);

-- idx_yahoo_rosters_league_key (INDEX)

CREATE INDEX idx_yahoo_rosters_league_key ON yahoo_rosters USING btree (league_key);

-- idx_yahoo_user_leagues_guid (INDEX)

CREATE INDEX idx_yahoo_user_leagues_guid ON yahoo_user_leagues USING btree (guid);

-- idx_yahoo_user_leagues_league_key (INDEX)

CREATE INDEX idx_yahoo_user_leagues_league_key ON yahoo_user_leagues USING btree (league_key);

-- markets_category_idx (INDEX)

CREATE INDEX markets_category_idx ON markets USING btree (category);

-- markets_event_ticker_idx (INDEX)

CREATE INDEX markets_event_ticker_idx ON markets USING btree (event_ticker);

-- markets_updated_at_idx (INDEX)

CREATE INDEX markets_updated_at_idx ON markets USING btree (updated_at);

-- support_drafts_thread_entry_uniq (INDEX)

CREATE UNIQUE INDEX support_drafts_thread_entry_uniq ON support_drafts USING btree (osticket_thread_entry_id) WHERE (osticket_thread_entry_id IS NOT NULL);

-- support_ticket_threads_thread_id_idx (INDEX)

CREATE INDEX support_ticket_threads_thread_id_idx ON support_ticket_threads USING btree (discord_thread_id);

-- user_deletion_requests_pending_purge_at (INDEX)

CREATE INDEX user_deletion_requests_pending_purge_at ON user_deletion_requests USING btree (purge_at) WHERE (status = 'pending'::text);

-- rss_items rss_items_feed_url_fkey (FK CONSTRAINT)

ALTER TABLE ONLY rss_items
    ADD CONSTRAINT rss_items_feed_url_fkey FOREIGN KEY (feed_url) REFERENCES tracked_feeds(url) ON DELETE CASCADE;

-- yahoo_matchups yahoo_matchups_league_key_fkey (FK CONSTRAINT)

ALTER TABLE ONLY yahoo_matchups
    ADD CONSTRAINT yahoo_matchups_league_key_fkey FOREIGN KEY (league_key) REFERENCES yahoo_leagues(league_key) ON DELETE CASCADE;

-- yahoo_rosters yahoo_rosters_league_key_fkey (FK CONSTRAINT)

ALTER TABLE ONLY yahoo_rosters
    ADD CONSTRAINT yahoo_rosters_league_key_fkey FOREIGN KEY (league_key) REFERENCES yahoo_leagues(league_key) ON DELETE CASCADE;

-- yahoo_standings yahoo_standings_league_key_fkey (FK CONSTRAINT)

ALTER TABLE ONLY yahoo_standings
    ADD CONSTRAINT yahoo_standings_league_key_fkey FOREIGN KEY (league_key) REFERENCES yahoo_leagues(league_key) ON DELETE CASCADE;

-- yahoo_user_leagues yahoo_user_leagues_guid_fkey (FK CONSTRAINT)

ALTER TABLE ONLY yahoo_user_leagues
    ADD CONSTRAINT yahoo_user_leagues_guid_fkey FOREIGN KEY (guid) REFERENCES yahoo_users(guid) ON DELETE CASCADE;

-- yahoo_user_leagues yahoo_user_leagues_league_key_fkey (FK CONSTRAINT)

ALTER TABLE ONLY yahoo_user_leagues
    ADD CONSTRAINT yahoo_user_leagues_league_key_fkey FOREIGN KEY (league_key) REFERENCES yahoo_leagues(league_key) ON DELETE CASCADE;

--
--

