// Command kbgen assembles the support knowledge base the AI triage prompt
// reads on every ticket (REL-242).
//
// The previous knowledge base was typed by hand and went stale within weeks:
// it named a version four minors old and denied widgets that had shipped.
// This one carries no product facts of its own. Every section is lifted from
// something that is already maintained for another reason — the design docs,
// the settings copy the app renders, the widget catalog the API serves, the
// published release notes — and carries a provenance line naming its source
// and the content hash it was read at. The only hand-written input is
// docs/support/POLICIES.md, for what code cannot know (refunds, wording,
// what never to say).
//
// Usage, from the api module root:
//
//	go run ./cmd/kbgen          # or `make kb` from the repo root
//
// Output is api/internal/support/kb/kb.generated.md, embedded into the
// binary. CI regenerates and diffs it, so a stale copy fails the build.
// GITHUB_TOKEN (or GH_TOKEN) is used for the releases request when set;
// unauthenticated works for a local run.
package main

import (
	"bytes"
	"crypto/sha1"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/brandon-relentnet/myscrollr/api/internal/platform"
	"github.com/brandon-relentnet/myscrollr/api/internal/widgets"
)

const (
	outPath     = "api/internal/support/kb/kb.generated.md"
	maxBytes    = 80 * 1024
	releasesURL = "https://api.github.com/repos/doughknee/myscrollr/releases?per_page=12"
	numReleases = 8
)

func main() {
	root := flag.String("root", "", "repo root (default: nearest ancestor holding desktop/package.json)")
	flag.Parse()

	if *root == "" {
		r, err := findRoot()
		if err != nil {
			fatal(err)
		}
		*root = r
	}
	doc, err := generate(*root)
	if err != nil {
		fatal(err)
	}
	if len(doc) > maxBytes {
		fatal(fmt.Errorf("knowledge base is %d bytes; the limit is %d — trim a source, not the limit", len(doc), maxBytes))
	}
	dest := filepath.Join(*root, filepath.FromSlash(outPath))
	if err := os.WriteFile(dest, doc, 0o644); err != nil {
		fatal(err)
	}
	fmt.Printf("wrote %s (%d bytes)\n", outPath, len(doc))
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "kbgen:", err)
	os.Exit(1)
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "desktop", "package.json")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("repo root not found (no desktop/package.json in any ancestor); pass -root")
		}
		dir = parent
	}
}

// source is one file read from the repo, LF-normalised so a Windows
// checkout hashes the same as CI.
type source struct {
	path string // repo-relative, forward slashes
	body string
	sha  string // git blob sha of the LF content, as `git hash-object` prints it
}

func read(root, rel string) (source, error) {
	b, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel)))
	if err != nil {
		return source{}, err
	}
	b = bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
	h := sha1.New()
	fmt.Fprintf(h, "blob %d\x00", len(b))
	h.Write(b)
	return source{path: rel, body: string(b), sha: hex.EncodeToString(h.Sum(nil))[:12]}, nil
}

func provenance(path, sha string) string {
	return fmt.Sprintf("<!-- source: %s @ %s -->\n", path, sha)
}

func generate(root string) ([]byte, error) {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }

	pkg, err := read(root, "desktop/package.json")
	if err != nil {
		return nil, err
	}
	var pkgJSON struct {
		Version string `json:"version"`
	}
	if err := json.Unmarshal([]byte(pkg.body), &pkgJSON); err != nil {
		return nil, fmt.Errorf("desktop/package.json: %w", err)
	}

	w("# Scrollr support knowledge base\n\n")
	w("<!-- GENERATED by `make kb` (api/cmd/kbgen). Do not edit. Each section names the file it was read from and the content hash it was read at; edit that file and regenerate. -->\n\n")
	w("This is the authoritative product reference for support replies. Anything stated here is ground truth; the Policies section says what may and may not be repeated to a user.\n\n")
	w("Current desktop version: **%s**.\n\n", pkgJSON.Version)
	w("%s\n", provenance(pkg.path, pkg.sha))

	// 1. Policies — first, because it carries the rules for reading the rest.
	pol, err := read(root, "docs/support/POLICIES.md")
	if err != nil {
		return nil, err
	}
	w("## Policies\n\n%s%s\n", provenance(pol.path, pol.sha), body(pol.body))

	// 2. What Scrollr is: the charter's product definition. Its later
	// sections are engineering decisions that name internal infrastructure,
	// which the document must not carry (POLICIES "Never say").
	vis, err := read(root, "docs/VISION.md")
	if err != nil {
		return nil, err
	}
	w("\n## What Scrollr is\n\n%s%s\n", provenance(vis.path, vis.sha),
		demote(sections(vis.body, "1. ")))

	// 3. Plans and limits, from the same table GET /tier-limits serves.
	w("\n## Plans and limits\n\n%s", provenance("api/internal/widgets/tier_limits.go (GET /tier-limits)", hashJSON(widgets.DefaultTierLimits)))
	w("The widget cap is the only per-plan limit. Plan names and wording are in Policies.\n\n")
	w("| Plan id | Widgets at once |\n|---|---|\n")
	for _, id := range tierOrder(widgets.DefaultTierLimits) {
		lim := widgets.DefaultTierLimits[id]
		cap := "unlimited"
		if lim.MaxWidgets != nil {
			cap = fmt.Sprint(*lim.MaxWidgets)
		}
		w("| `%s` | %s |\n", id, cap)
	}

	// 4. The widget catalog, from the same data GET /catalog serves.
	cat := platform.Catalog()
	w("\n## Widget catalog\n\n%s", provenance("api/internal/platform/widgets.go (GET /catalog)", hashJSON(cat)))
	w("%d widgets. Every widget costs one slot. A widget marked *off the add grid* cannot be added right now, but anyone who already has it keeps it.\n", len(cat))
	writeCatalog(&b, cat)

	// 5. Settings, one line per rendered row, in the app's own words.
	pages, err := read(root, "desktop/src/components/settings/pages.ts")
	if err != nil {
		return nil, err
	}
	rows, err := read(root, "desktop/src/components/settings/rows.ts")
	if err != nil {
		return nil, err
	}
	w("\n## Settings\n\n%s%s", provenance(pages.path, pages.sha), provenance(rows.path, rows.sha))
	w("Every settings row, as the app labels it. \"Signed in\" / \"signed out\" marks rows that only exist in that state.\n")
	if err := writeSettings(&b, pages.body, rows.body); err != nil {
		return nil, err
	}

	// 6. How the ticker works.
	chip, err := read(root, "docs/CHIP_DESIGN.md")
	if err != nil {
		return nil, err
	}
	w("\n## How the ticker works\n\n%s%s\n", provenance(chip.path, chip.sha), body(chip.body))

	// 7. The settings model. The audit was written against v1.5.2; its
	// "Today" columns describe the app before the 1.6.0 rebuild and its
	// verdicts are what shipped. The Settings section above is current.
	aud, err := read(root, "docs/SETTINGS_AUDIT.md")
	if err != nil {
		return nil, err
	}
	w("\n## The settings model\n\n%s", provenance(aud.path, aud.sha))
	w("Excerpt (sections 1–3) of the settings audit that shaped the 1.6.0 Settings rebuild. Its \"Today\" columns describe the app *before* that rebuild; the Settings section above is what the app shows now.\n\n")
	w("%s\n", demote(sections(aud.body, "1. ", "2. ", "3. ")))

	// 8. Shipped releases, from the roadmap's summary table.
	road, err := read(root, "docs/ROADMAP.md")
	if err != nil {
		return nil, err
	}
	w("\n## Release history\n\n%s%s\n", provenance(road.path, road.sha), shippedRows(road.body))

	// 9. The last N release notes, as published.
	rels, err := fetchReleases()
	if err != nil {
		return nil, err
	}
	w("\n## Recent release notes\n\n%s", provenance("github.com/doughknee/myscrollr/releases", rels[0].Tag))
	w("The last %d published releases, newest first, as users read them.\n", len(rels))
	for _, r := range rels {
		w("\n### %s (`%s`, %s)\n\n%s\n", r.Name, r.Tag, r.PublishedAt.Format("2006-01-02"), demote(demote(strings.TrimSpace(r.Body))))
	}

	return []byte(b.String()), nil
}

func hashJSON(v any) string {
	raw, err := json.Marshal(v)
	if err != nil {
		return "unmarshallable"
	}
	sum := sha256.Sum256(raw)
	return hex.EncodeToString(sum[:8])
}

// tierOrder sorts plans lowest first, using the same priority the API
// uses to pick a user's tier from their roles.
func tierOrder(m map[string]widgets.WidgetLimits) []string {
	ids := make([]string, 0, len(m))
	for id := range m {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool {
		return platform.TierFromRoles([]string{ids[i], ids[j]}) == ids[j]
	})
	return ids
}

func writeCatalog(b *strings.Builder, cat []platform.WidgetDef) {
	// Catalog order groups by category already; emit a heading per
	// category as it changes.
	var cur string
	for _, wd := range cat {
		if wd.Category != cur {
			cur = wd.Category
			fmt.Fprintf(b, "\n### %s\n\n", strings.ToUpper(cur[:1])+cur[1:])
		}
		fmt.Fprintf(b, "- **%s**", wd.Name)
		if wd.Group != "" {
			fmt.Fprintf(b, " (%s)", wd.Group)
		}
		fmt.Fprintf(b, " — %s", strings.TrimSpace(wd.Description))
		if wd.Hidden {
			b.WriteString(" *Off the add grid.*")
		}
		if wd.RequiredTier != "" && wd.RequiredTier != "free" {
			fmt.Fprintf(b, " Requires plan `%s`.", wd.RequiredTier)
		}
		if len(wd.Usage) > 0 {
			fmt.Fprintf(b, " *How to use:* %s", strings.Join(wd.Usage, " "))
		}
		b.WriteString("\n")
	}
}

var (
	rePageLabel = regexp.MustCompile(`(?m)^  (\w+): \{\s*id: "\w+",\s*label: "([^"]*)"`)
	rePage      = regexp.MustCompile(`^  (\w+): \{$`)
	reRow       = regexp.MustCompile(`^    (\w+): \{$`)
	reLabel     = regexp.MustCompile(`label:\s*"([^"]*)"`)
	reDesc      = regexp.MustCompile(`description:\s*"([^"]*)"`)
	reWhen      = regexp.MustCompile(`when:\s*"(\w+)"`)
	reWrapped   = regexp.MustCompile(`:\s*\n\s*"`)
)

// writeSettings renders rows.ts as "Settings › Page › Row: description".
// rows.ts is data, not code: an object literal two levels deep with string
// fields, which is why a regex reading is enough and a TS parser is not.
func writeSettings(b *strings.Builder, pagesTS, rowsTS string) error {
	labels := map[string]string{}
	for _, m := range rePageLabel.FindAllStringSubmatch(pagesTS, -1) {
		labels[m[1]] = m[2]
	}
	if len(labels) == 0 {
		return errors.New("pages.ts: no page labels found; the file shape changed")
	}

	// Collapse the multi-line `description:\n  "..."` form so one regex
	// reads both layouts, then walk the file line by line.
	rowsTS = reWrapped.ReplaceAllString(rowsTS, `: "`)
	var page, rowKey, rowBuf string
	n := 0
	for _, line := range strings.Split(rowsTS, "\n") {
		switch {
		case rePage.MatchString(line):
			page = rePage.FindStringSubmatch(line)[1]
			label, ok := labels[page]
			if !ok {
				return fmt.Errorf("rows.ts: page %q has no label in pages.ts", page)
			}
			fmt.Fprintf(b, "\n### Settings › %s\n\n", label)
		case reRow.MatchString(line):
			rowKey = reRow.FindStringSubmatch(line)[1]
			rowBuf = ""
		case rowKey != "" && line == "    },":
			l, d := reLabel.FindStringSubmatch(rowBuf), reDesc.FindStringSubmatch(rowBuf)
			if l == nil || d == nil {
				return fmt.Errorf("rows.ts: row %s.%s lacks a label or description", page, rowKey)
			}
			fmt.Fprintf(b, "- Settings › %s › %s: %s", labels[page], l[1], d[1])
			if wm := reWhen.FindStringSubmatch(rowBuf); wm != nil {
				fmt.Fprintf(b, " *(%s only)*", map[string]string{"signedIn": "signed in", "signedOut": "signed out"}[wm[1]])
			}
			b.WriteString("\n")
			n++
			rowKey = ""
		case rowKey != "":
			rowBuf += line + "\n"
		}
	}
	if n == 0 {
		return errors.New("rows.ts: no rows found; the file shape changed")
	}
	return nil
}

// sections returns the H2 sections of a markdown document whose heading
// text starts with one of the given prefixes, in document order.
func sections(md string, prefixes ...string) string {
	var out []string
	var cur []string
	keep := false
	flush := func() {
		if keep && len(cur) > 0 {
			s := strings.TrimSpace(strings.Join(cur, "\n"))
			// Sections in these docs end with a "---" rule; drop it so the
			// joined text does not read as a broken table.
			out = append(out, strings.TrimSpace(strings.TrimSuffix(s, "---")))
		}
		cur = nil
	}
	for _, line := range strings.Split(md, "\n") {
		if strings.HasPrefix(line, "## ") {
			flush()
			keep = false
			for _, p := range prefixes {
				if strings.HasPrefix(line[3:], p) {
					keep = true
				}
			}
		}
		cur = append(cur, line)
	}
	flush()
	return strings.Join(out, "\n\n")
}

// body prepares a whole document for embedding: its H1 title goes (the
// section heading already names it) and the rest nests one level down.
func body(md string) string {
	md = strings.TrimSpace(md)
	if strings.HasPrefix(md, "# ") {
		if _, rest, ok := strings.Cut(md, "\n"); ok {
			md = strings.TrimSpace(rest)
		}
	}
	return demote(md)
}

// demote pushes every markdown heading down one level so an embedded
// document nests under the section that holds it.
func demote(md string) string {
	lines := strings.Split(md, "\n")
	fenced := false
	for i, l := range lines {
		if strings.HasPrefix(l, "```") {
			fenced = !fenced
		}
		if !fenced && strings.HasPrefix(l, "#") {
			lines[i] = "#" + l
		}
	}
	return strings.Join(lines, "\n")
}

// shippedRows keeps the roadmap summary table's header and every row
// marked shipped, with the strikethrough removed.
func shippedRows(md string) string {
	var out []string
	for _, line := range strings.Split(md, "\n") {
		switch {
		case strings.HasPrefix(line, "| Version"), strings.HasPrefix(line, "|---"):
			if len(out) < 2 {
				out = append(out, line)
			}
		case strings.HasPrefix(line, "|") && strings.Contains(line, "✅"):
			out = append(out, strings.ReplaceAll(line, "~~", ""))
		}
	}
	return strings.Join(out, "\n")
}

type release struct {
	Tag         string    `json:"tag_name"`
	Name        string    `json:"name"`
	Body        string    `json:"body"`
	Draft       bool      `json:"draft"`
	Prerelease  bool      `json:"prerelease"`
	PublishedAt time.Time `json:"published_at"`
}

func fetchReleases() ([]release, error) {
	req, err := http.NewRequest(http.MethodGet, releasesURL, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "myscrollr-kbgen")
	for _, k := range []string{"GITHUB_TOKEN", "GH_TOKEN"} {
		if t := os.Getenv(k); t != "" {
			req.Header.Set("Authorization", "Bearer "+t)
			break
		}
	}
	resp, err := (&http.Client{Timeout: 30 * time.Second}).Do(req)
	if err != nil {
		return nil, fmt.Errorf("releases: %w", err)
	}
	defer resp.Body.Close()
	raw, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("releases: %s: %s", resp.Status, strings.TrimSpace(string(raw)))
	}
	var all []release
	if err := json.Unmarshal(raw, &all); err != nil {
		return nil, fmt.Errorf("releases: %w", err)
	}
	var out []release
	for _, r := range all {
		if r.Draft || r.Prerelease {
			continue
		}
		r.Body = strings.ReplaceAll(r.Body, "\r\n", "\n")
		out = append(out, r)
		if len(out) == numReleases {
			break
		}
	}
	if len(out) == 0 {
		return nil, errors.New("releases: none published")
	}
	return out, nil
}
