/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as CustomizeRouteImport } from './routes/customize'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetIdIndexRouteImport } from './routes/widget.$id.index'
import { Route as WidgetIdInfoRouteImport } from './routes/widget.$id.info'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeRoute = CustomizeRouteImport.update({
  id: '/customize',
  path: '/customize',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetIdIndexRoute = WidgetIdIndexRouteImport.update({
  id: '/widget/$id/',
  path: '/widget/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetIdInfoRoute = WidgetIdInfoRouteImport.update({
  id: '/widget/$id/info',
  path: '/widget/$id/info',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/catalog': typeof CatalogRoute
  '/customize': typeof CustomizeRoute
  '/feed': typeof FeedRoute
  '/releases': typeof ReleasesRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/widget/$id/info': typeof WidgetIdInfoRoute
  '/widget/$id/': typeof WidgetIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/catalog': typeof CatalogRoute
  '/customize': typeof CustomizeRoute
  '/feed': typeof FeedRoute
  '/releases': typeof ReleasesRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/widget/$id/info': typeof WidgetIdInfoRoute
  '/widget/$id': typeof WidgetIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/catalog': typeof CatalogRoute
  '/customize': typeof CustomizeRoute
  '/feed': typeof FeedRoute
  '/releases': typeof ReleasesRoute
  '/status': typeof StatusRoute
  '/support': typeof SupportRoute
  '/widget/$id/info': typeof WidgetIdInfoRoute
  '/widget/$id/': typeof WidgetIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/catalog'
    | '/customize'
    | '/feed'
    | '/releases'
    | '/status'
    | '/support'
    | '/widget/$id/info'
    | '/widget/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/catalog'
    | '/customize'
    | '/feed'
    | '/releases'
    | '/status'
    | '/support'
    | '/widget/$id/info'
    | '/widget/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/catalog'
    | '/customize'
    | '/feed'
    | '/releases'
    | '/status'
    | '/support'
    | '/widget/$id/info'
    | '/widget/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CatalogRoute: typeof CatalogRoute
  CustomizeRoute: typeof CustomizeRoute
  FeedRoute: typeof FeedRoute
  ReleasesRoute: typeof ReleasesRoute
  StatusRoute: typeof StatusRoute
  SupportRoute: typeof SupportRoute
  WidgetIdInfoRoute: typeof WidgetIdInfoRoute
  WidgetIdIndexRoute: typeof WidgetIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize': {
      id: '/customize'
      path: '/customize'
      fullPath: '/customize'
      preLoaderRoute: typeof CustomizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$id/': {
      id: '/widget/$id/'
      path: '/widget/$id'
      fullPath: '/widget/$id/'
      preLoaderRoute: typeof WidgetIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$id/info': {
      id: '/widget/$id/info'
      path: '/widget/$id/info'
      fullPath: '/widget/$id/info'
      preLoaderRoute: typeof WidgetIdInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CatalogRoute: CatalogRoute,
  CustomizeRoute: CustomizeRoute,
  FeedRoute: FeedRoute,
  ReleasesRoute: ReleasesRoute,
  StatusRoute: StatusRoute,
  SupportRoute: SupportRoute,
  WidgetIdInfoRoute: WidgetIdInfoRoute,
  WidgetIdIndexRoute: WidgetIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
