//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

export default [
  ...tanstackConfig,
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      // Generated by api/cmd/gents — must stay byte-identical to the
      // generator output (TestGeneratedTypesAreCurrent compares exactly),
      // so neither eslint --fix nor prettier may reformat it.
      'src/types/api.generated.ts',
    ],
  },
]
