#!/usr/bin/env bash
#
# `make seed` / `make seed-capture` — the local dev dataset.
#
# Local dev runs with every upstream API key blank (see scripts/dev/setup.mjs).
# The ingesters handle that correctly: they stay up and serve whatever is in
# Postgres. But a fresh clone's Postgres is EMPTY, so the honest reward for
# `make up` was a blank app, and the only way to see a working one was to paste
# a production key — spending the same api-sports and TwelveData quota that live
# users depend on.
#
# This loads a committed snapshot instead. Zero upstream requests, ever.
#
#   seed.sh load      restore scripts/dev/seed.sql.gz into the local stack
#   seed.sh capture   re-record that snapshot from $SOURCE_DATABASE_URL
#
# Capture is a rare maintenance operation; `load` is what everyone runs.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SEED_FILE="${SEED_FILE:-$ROOT/scripts/dev/seed.sql.gz}"
COMPOSE=(docker compose -f "$ROOT/docker/compose.yml")
[ -f "$ROOT/docker/compose.override.yml" ] && COMPOSE+=(-f "$ROOT/docker/compose.override.yml")

# The local stack's own database. Capture defaults to this too, so the common
# case (run once with real keys, snapshot the result) needs no arguments.
LOCAL_DB="postgres://scrollr:scrollr@localhost:5432/scrollr?sslmode=disable"

# psql runs inside the postgres container — no host Postgres client required,
# which is the whole point of the containerized stack. A remote
# SOURCE_DATABASE_URL is resolved from inside that container: use
# host.docker.internal for a `kubectl port-forward` on the host.
psql_in() {
  local url="$1"; shift
  "${COMPOSE[@]}" exec -T postgres psql "$url" -v ON_ERROR_STOP=1 "$@"
}

redis_in() {
  "${COMPOSE[@]}" exec -T redis redis-cli "$@"
}

# ── The dataset ──────────────────────────────────────────────────────
# table|WHERE/LIMIT clause. These ten tables are ALL content, no user data —
# the allowlist is the entire scrub. Everything with user data in it
# (yahoo_*, user_*, stripe_*, support_*, business_leads, osticket_*) is
# excluded by not being here.
#
# Order matters on load: rss_items has an FK onto tracked_feeds(url).
TABLES='
tracked_symbols|
tracked_leagues|
tracked_markets|
tracked_feeds|WHERE is_default = true
trades|
games|
standings|
teams|
markets|ORDER BY close_time DESC NULLS LAST LIMIT 500
rss_items|WHERE feed_url IN (SELECT url FROM tracked_feeds WHERE is_default = true) ORDER BY published_at DESC NULLS LAST LIMIT 500
'

# Read into an array once, up front. A `while read` loop fed by a pipe or
# here-string silently stops after ONE iteration here, because the body calls
# `docker compose exec`, which inherits stdin and drains it. That failure looks
# like a successful capture holding a single table.
SPECS=()
while IFS= read -r line; do
  [ -n "$line" ] && SPECS+=("$line")
done <<< "$TABLES"

table_names() { printf '%s
' "${SPECS[@]}" | cut -d'|' -f1; }

# ── capture ──────────────────────────────────────────────────────────
capture() {
  local src="${SOURCE_DATABASE_URL:-$LOCAL_DB}"
  # File-scope, not `local`: the EXIT trap runs after this function has
  # returned, where a local would already be out of scope and `set -u` would
  # turn cleanup itself into an error.
  TMP_SEED="$(mktemp)"
  trap 'rm -f "${TMP_SEED:-}"' EXIT
  local tmp="$TMP_SEED"

  echo "[seed] capturing from ${src%%\?*}"

  {
    echo "-- Generated by scripts/dev/seed.sh capture on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
    echo "-- Content tables only — no user data. Do not edit by hand; re-run capture."
    echo "BEGIN;"
    # One TRUNCATE for all ten: rss_items -> tracked_feeds is an FK, and
    # naming both in the same statement is what makes that legal without
    # CASCADE (which would reach into user tables).
    echo "TRUNCATE $(table_names | paste -sd, -) RESTART IDENTITY;"
  } > "$tmp"

  local spec table clause
  for spec in "${SPECS[@]}"; do
    table="${spec%%|*}"; clause="${spec#*|}"
    # Explicit column list, resolved at capture time and written into the
    # COPY header. That makes the file self-describing: a column ADDED later
    # still loads (it takes its default), and a column DROPPED fails loudly
    # on load instead of silently shifting every value one place left.
    local cols
    cols="$(psql_in "$src" -At -c \
      "SELECT string_agg(quote_ident(column_name), ', ' ORDER BY ordinal_position)
         FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = '$table'")"
    if [ -z "$cols" ]; then
      echo "[seed] ERROR: table '$table' does not exist in the source database" >&2
      exit 1
    fi

    echo "COPY $table ($cols) FROM stdin;" >> "$tmp"
    psql_in "$src" -At -c "COPY (SELECT $cols FROM $table $clause) TO STDOUT" >> "$tmp"
    echo '\.' >> "$tmp"

    # Wrapped in a subquery: the clause may be an ORDER BY/LIMIT, which
    # Postgres rejects directly against a bare count(*).
    local n; n="$(psql_in "$src" -At -c "SELECT count(*) FROM (SELECT 1 FROM $table $clause) q")"
    printf '  %-18s %s rows\n' "$table" "$n"
  done

  echo "COMMIT;" >> "$tmp"
  gzip -9 -c "$tmp" > "$SEED_FILE"
  echo "[seed] wrote $SEED_FILE ($(du -h "$SEED_FILE" | cut -f1))"
  echo "[seed] commit it — that file IS the dev dataset."
}

# ── load ─────────────────────────────────────────────────────────────
# Restoring rows is only half the job. Several read paths and one background
# job are time-relative, so a snapshot restored months later is present in the
# database and invisible (or self-deleting) in the app. Each shift below is
# tied to the specific query that demands it — verified by reading them, not
# assumed:
#
#   rss_items     the RSS ingester DELETEs published_at < now() - 7 days
#                 (channels/rss/service/src/database.rs:303). Unshifted seed
#                 articles are purged on its first cycle.
#   tracked_feeds the catalog hides feeds unless last_success_at is NULL or
#                 under 7 days old (api/internal/ingestread/rss.go:158), and
#                 the janitor DISABLES feeds that are NULL and created over
#                 7 days ago (rss.go:727). NULL + fresh created_at satisfies
#                 both: visible, and never auto-disabled. is_enabled is forced
#                 back on for the same reason — whichever machine the snapshot
#                 was captured on had almost certainly let the janitor run and
#                 switch the curated feeds off, and capturing that state ships
#                 a dataset whose RSS catalog is silently empty.
#   markets       predictions only returns close_time > now()
#                 (api/internal/ingestread/predictions.go:89).
#   games         no filter — purely cosmetic, so that 'pre' games are still
#                 in the future and the ticker looks like a real day.
#
# trades, standings, teams and the tracked_* config tables carry no
# time-relative read, so they are restored as-is.
REBASE_SQL="
-- ONE delta for everything, taken from the freshest WRITE in the snapshot.
--
-- The first version of this anchored each table on the max of the column it
-- was shifting -- for games, max(start_time). That is the wrong end of the
-- data. A snapshot contains fixtures scheduled far beyond \"now\": the F1
-- calendar runs months ahead, so pinning the LAST race to now+3h dragged every
-- other league backwards with it and landed the entire MLB and MLS schedule in
-- May, four months in the past. Zero games fell inside the +/-7 day window the
-- widgets filter on, so a correctly working app rendered nothing.
--
-- max(updated_at) is when the ingester last wrote a row, which approximates
-- the moment of capture. Shifting everything by (now - that) preserves each
-- record's true relationship to \"now\": a game that was two days out when the
-- snapshot was taken is two days out today, and a fixture scheduled months
-- ahead stays months ahead.
--
-- updated_at itself is deliberately NOT shifted, so the anchor stays stable
-- across the statements below. Nothing reads it for staleness -- the ingesters
-- track freshness in memory, and the RSS janitor uses tracked_feeds, handled
-- separately below.
-- Every id sequence is left behind by the load itself. The file opens with
-- TRUNCATE ... RESTART IDENTITY, which resets each sequence to 1, and then
-- COPYs rows carrying EXPLICIT ids -- and COPY does not advance a sequence.
-- So after a seed the data runs to (say) id 418088 while the sequence still
-- hands out 1, and the next INSERT that relies on it collides on the primary
-- key. That breaks the RSS ingester (the one service that polls with no API
-- key) and any test that inserts a fixture row. Catch every seeded table up.
DO \$\$
DECLARE t text; seq text; mx bigint;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'tracked_symbols','tracked_leagues','tracked_markets','tracked_feeds',
    'trades','games','standings','teams','markets','rss_items'
  ] LOOP
    -- Check the column exists FIRST. pg_get_serial_sequence RAISES on a
    -- missing column rather than returning NULL, and one raise aborts the
    -- whole DO block -- which silently left the tables listed after
    -- tracked_feeds (games, trades, rss_items) still broken.
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public' AND table_name = t AND column_name = 'id'
    ) THEN
      seq := pg_get_serial_sequence(t, 'id');
      IF seq IS NOT NULL THEN
        EXECUTE format('SELECT COALESCE(max(id), 0) FROM %I', t) INTO mx;
        PERFORM setval(seq, GREATEST(mx, 1));
      END IF;
    END IF;
  END LOOP;
END
\$\$;

UPDATE games SET start_time = start_time + (now() - (SELECT max(updated_at) FROM games))
  WHERE start_time IS NOT NULL
    AND (SELECT max(updated_at) FROM games) IS NOT NULL;

UPDATE rss_items SET published_at = published_at + (now() - (SELECT max(updated_at) FROM games))
  WHERE published_at IS NOT NULL
    AND (SELECT max(updated_at) FROM games) IS NOT NULL;

UPDATE markets SET close_time = close_time + (now() - (SELECT max(updated_at) FROM games))
  WHERE close_time IS NOT NULL
    AND (SELECT max(updated_at) FROM games) IS NOT NULL;

UPDATE tracked_feeds SET last_success_at = NULL,
                         created_at = now(),
                         consecutive_failures = 0,
                         last_error = NULL,
                         last_error_at = NULL,
                         is_enabled = true;
"

load() {
  [ -f "$SEED_FILE" ] || { echo "[seed] no dataset at $SEED_FILE (run: make seed-capture)" >&2; exit 1; }

  if ! "${COMPOSE[@]}" ps --status running --services 2>/dev/null | grep -qx postgres; then
    echo "[seed] postgres is not running — start the stack first (make up)." >&2
    exit 1
  fi

  echo "[seed] loading $SEED_FILE"
  # The file is one BEGIN/COMMIT with a TRUNCATE at the top, so a re-seed
  # replaces the dataset rather than duplicating it, and a failure part-way
  # leaves the previous contents intact.
  gzip -dc "$SEED_FILE" | psql_in "$LOCAL_DB" -q

  echo "[seed] rebasing timestamps to now"
  psql_in "$LOCAL_DB" -q -c "$REBASE_SQL"

  # Core caches every widget read in Redis for 10-30s (cache:finance,
  # cache:sports, cache:public:feed, ...). Seeding changes the data those
  # entries describe without touching the entries themselves, so without this
  # the app keeps serving the PRE-seed answer for up to half a minute — long
  # enough for a human to conclude the seed did not work, and long enough to
  # fail a CI step that seeds and asserts back to back.
  #
  # Scoped to cache:* rather than FLUSHALL: Redis also holds SSE subscriber
  # sets and channel registrations that have nothing to do with seeding.
  echo "[seed] dropping stale read caches"
  local keys
  keys="$(redis_in --scan --pattern 'cache:*' | tr -d '
')"
  if [ -n "$keys" ]; then
    # Unquoted on purpose: split the key list into one DEL with many
    # arguments. (xargs is not an option here — redis_in is a shell function.)
    # shellcheck disable=SC2086
    redis_in DEL $keys >/dev/null 2>&1 || true
  fi

  echo "[seed] loaded:"
  local spec table
  for spec in "${SPECS[@]}"; do
    table="${spec%%|*}"
    printf '  %-18s %s rows
' "$table" "$(psql_in "$LOCAL_DB" -At -c "SELECT count(*) FROM $table")"
  done

  echo "[seed] done — no upstream API requests were made."
}

case "${1:-}" in
  load)    load ;;
  capture) capture ;;
  *) echo "usage: seed.sh {load|capture}" >&2; exit 2 ;;
esac
