#!/usr/bin/env node
/**
 * `make setup` — generate every .env file this repo needs.
 *
 * Before this existed, a fresh clone meant hand-assembling 7 env files, one
 * of which (api/.env, ~65 vars read) had no template at all. Now: answer a
 * handful of questions once, or accept the defaults and get a stack that
 * boots without auth.
 *
 * Safe to re-run. Existing files are never overwritten without --force;
 * missing keys are appended to files that already exist.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const FORCE = process.argv.includes("--force");
const PREDICTIONS_ONLY = process.argv.includes("--predictions-only");
const p = (...s) => path.join(ROOT, ...s);

// ── Shared values ────────────────────────────────────────────────────
// ENCRYPTION_KEY must be IDENTICAL across core and every channel: core
// encrypts third-party tokens (Yahoo, Kalshi) and the channels decrypt
// them. Generating it per-file would produce a stack that runs and then
// fails to read its own data.
const DB = "postgres://scrollr:scrollr@localhost:5432/scrollr?sslmode=disable";
const REDIS = "redis://localhost:6379";

function existingKey(...files) {
  for (const f of files) {
    if (!existsSync(p(f))) continue;
    const m = readFileSync(p(f), "utf8").match(/^ENCRYPTION_KEY=(.+)$/m);
    if (m && m[1].trim()) return m[1].trim();
  }
  return null;
}

// ── Templates ────────────────────────────────────────────────────────
const files = (enc, logto) => ({
  "api/.env": `# Generated by \`make setup\`. Safe to edit.
DATABASE_URL=${DB}
REDIS_URL=${REDIS}
PORT=8080
# NOT an address — core only ever uses API_URL as the OIDC \`resource\` it
# requests and the \`aud\` it validates on incoming tokens. Logto issues
# tokens for the resource it has registered, which is the production
# identifier even when you are calling localhost, so pointing this at
# localhost rejects every token with "invalid token audience". Same
# reasoning as VITE_LOGTO_RESOURCE below.
API_URL=https://api.myscrollr.com
FRONTEND_URL=http://localhost:3000
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5174,tauri://localhost
ENVIRONMENT=development
STRIPE_DISABLED=true
ENCRYPTION_KEY=${enc}
# The /oidc form: core builds its token endpoint as LOGTO_URL + "/token"
# and compares it against the token's \`iss\`. The bare tenant domain 404s
# on token exchange and rejects every token as "invalid token issuer".
LOGTO_URL=${logto.issuer}
LOGTO_JWKS_URL=${logto.jwks}
LOGTO_EXTENSION_APP_ID=${logto.appId}
LOGTO_UPLINK_ROLE_ID=
LOGTO_PRO_ROLE_ID=
LOGTO_ULTIMATE_ROLE_ID=
LOGTO_SUPER_USER_ROLE_ID=
`,
  "channels/finance/.env": `DATABASE_URL=${DB}
PORT=3001
ENCRYPTION_KEY=${enc}
# Optional: without a key the finance ingester serves whatever is already
# in the database and logs that it is not polling.
TWELVEDATA_API_KEY=
`,
  "channels/sports/.env": `DATABASE_URL=${DB}
PORT=3002
ENCRYPTION_KEY=${enc}
# Optional: without a key the sports ingester serves whatever is already
# in the database and logs that it is not polling.
API_SPORTS_KEY=
`,
  "channels/rss/.env": `DATABASE_URL=${DB}
PORT=3004
ENCRYPTION_KEY=${enc}
`,
  "channels/fantasy/.env": `DATABASE_URL=${DB}
REDIS_URL=${REDIS}
PORT=8084
ENCRYPTION_KEY=${enc}
CHANNEL_URL=http://localhost:8084
# Yahoo OAuth. Without these the fantasy widget cannot connect an account;
# everything else in the stack runs fine.
YAHOO_CLIENT_ID=
YAHOO_CLIENT_SECRET=
YAHOO_CALLBACK_URL=http://localhost:8084/yahoo/callback
`,
  // The marketing site. Stripe price ids are the real test-mode ones from
  // .env.example — they're not secret and the pricing page needs them to
  // render. The publishable key is a placeholder; billing flows won't work
  // until you supply a real pk_test_.
  "myscrollr.com/.env": `VITE_API_URL=http://localhost:18080
VITE_LOGTO_ENDPOINT=${logto.url}
VITE_LOGTO_APP_ID=${logto.webAppId}
VITE_LOGTO_RESOURCE=https://api.myscrollr.com
VITE_STRIPE_PUBLISHABLE_KEY=pk_test_REPLACE_ME
VITE_STRIPE_PRICE_MONTHLY=price_1TMyBUFk6czwHVgrocQKaBHD
VITE_STRIPE_PRICE_ANNUAL=price_1TMyBUFk6czwHVgr2AysFrfL
VITE_STRIPE_PRICE_PRO_MONTHLY=price_1TMyBUFk6czwHVgrc6YHoQoj
VITE_STRIPE_PRICE_PRO_ANNUAL=price_1TMyBVFk6czwHVgrN2oUq6fx
VITE_STRIPE_PRICE_ULTIMATE_MONTHLY=price_1TMyBVFk6czwHVgriAztoY86
VITE_STRIPE_PRICE_ULTIMATE_ANNUAL=price_1TMyBVFk6czwHVgr9ntOrMXf
VITE_SENTRY_DSN=
SENTRY_ORG=
SENTRY_AUTH_TOKEN=
`,
  "desktop/.env": `# The desktop app talks to the LOCAL core API.
VITE_API_URL=http://localhost:18080
VITE_AUTH_ENDPOINT=${logto.url}
VITE_LOGTO_APP_ID=${logto.desktopAppId}
# Logto only knows the resources it has registered, so the token is
# requested for the PROD API resource while the app calls the local one.
# Without this, sign-in fails with "resource indicator is missing, or unknown".
VITE_LOGTO_RESOURCE=https://api.myscrollr.com
# Sentry stays off locally.
VITE_SENTRY_DSN=
SENTRY_DSN_RUST=
SENTRY_ORG=
SENTRY_AUTH_TOKEN=
`,
});

// ── Predictions (opt-in) ─────────────────────────────────────────────
// The Kalshi private key is a multiline PEM that Docker's env_file cannot
// parse, so it goes to its own file and the service reads a path instead.
function writePredictions() {
  const pem = p("secrets/kalshi-private-key.pem");
  if (!existsSync(pem)) {
    console.log("  skip  predictions   no Kalshi key yet (run: make kalshi-key)");
    return;
  }
  mkdirSync(p("secrets"), { recursive: true });
  const enc = existingKey("api/.env") ?? "";
  const out = p("secrets/predictions.docker.env");
  if (existsSync(out) && !FORCE) {
    console.log("  keep  predictions   already configured");
    return;
  }
  writeFileSync(
    out,
    `DATABASE_URL=postgres://scrollr:scrollr@postgres:5432/scrollr?sslmode=disable
PORT=3005
ENCRYPTION_KEY=${enc}
KALSHI_API_KEY_ID=
`,
    "utf8",
  );
  console.log("  wrote predictions   secrets/predictions.docker.env");
  console.log("        -> add your KALSHI_API_KEY_ID to that file");
}

// ── Main ─────────────────────────────────────────────────────────────
if (PREDICTIONS_ONLY) {
  writePredictions();
  process.exit(0);
}

// Prompt only when there's a human attached. Piped or redirected stdin
// (CI, `yes |`, a script) takes every default instead of hanging forever on
// a question nobody will answer.
const INTERACTIVE = process.stdin.isTTY === true;
const rl = INTERACTIVE
  ? createInterface({ input: process.stdin, output: process.stdout })
  : null;

const ask = async (q, dflt = "") => {
  if (!rl) return dflt;
  const a = (await rl.question(dflt ? `${q} [${dflt}]: ` : `${q}: `)).trim();
  return a || dflt;
};

if (!INTERACTIVE) {
  console.log("setup: no TTY detected - taking every default (no prompts).");
}

console.log(`
  MyScrollr setup
  ---------------
  Generates the .env files for local development.

  Everything below has a working default except the Logto values. You can
  press enter through all of them: the stack will boot and serve public
  data, you just won't be able to sign in until you fill them in.
`);

const enc =
  existingKey("api/.env", "channels/fantasy/.env") ??
  randomBytes(32).toString("hex");

const logto = {
  url: await ask("Logto URL (blank = no auth)", ""),
  issuer: "",
  jwks: "",
  appId: await ask("Logto extension app id", ""),
  desktopAppId: await ask("Logto DESKTOP app id", ""),
  webAppId: await ask("Logto WEBSITE app id", ""),
};
// Everything below hangs off the tenant URL — derive rather than ask
// four times. The bare URL is what the Logto SDKs want (they append
// /oidc themselves, so VITE_LOGTO_ENDPOINT and VITE_AUTH_ENDPOINT must
// NOT carry it); core talks to the OIDC endpoints directly and needs the
// /oidc form for both the token endpoint and the `iss` it validates.
{
  const base = logto.url.replace(/\/$/, "");
  logto.url = base;
  logto.issuer = base ? `${base}/oidc` : "";
  logto.jwks = base ? `${base}/oidc/jwks` : "";
}

rl?.close();

console.log("");
let wrote = 0;
for (const [rel, body] of Object.entries(files(enc, logto))) {
  const dest = p(rel);
  if (existsSync(dest) && !FORCE) {
    console.log(`  keep  ${rel.padEnd(24)} exists (--force to overwrite)`);
    continue;
  }
  mkdirSync(path.dirname(dest), { recursive: true });
  writeFileSync(dest, body, "utf8");
  console.log(`  wrote ${rel}`);
  wrote++;
}
writePredictions();

console.log(`
  ${wrote} file(s) written. ENCRYPTION_KEY is shared across all of them --
  core encrypts third-party tokens and the channels decrypt them, so they
  must match.

  Next:  make up
`);
