#!/usr/bin/env node
/**
 * `make setup` — generate every .env file this repo needs.
 *
 * Before this existed, a fresh clone meant hand-assembling 7 env files, one
 * of which (api/.env, ~65 vars read) had no template at all. Now: answer a
 * handful of questions once, or accept the defaults and get a stack that
 * boots without auth.
 *
 * Safe to re-run. Existing files are never overwritten without --force;
 * missing keys are appended to files that already exist.
 */
import { existsSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const FORCE = process.argv.includes("--force");
const p = (...s) => path.join(ROOT, ...s);

// ── Shared values ────────────────────────────────────────────────────
// ENCRYPTION_KEY must be IDENTICAL across core and every channel: core
// encrypts third-party tokens and the channels decrypt them. Generating
// it per-file would produce a stack that runs and then fails to read
// its own data.
const DB = "postgres://scrollr:scrollr@localhost:5432/scrollr?sslmode=disable";
const REDIS = "redis://localhost:6379";

// `make setup DEV_API=remote`: front-end-only work against the always-on dev
// backend (docker/compose.dev-remote.yml). Only the two front-end .env files
// are written -- there is no local backend to configure -- and their API base
// points at it instead of localhost:18080. DEV_API_URL overrides the address.
const REMOTE = process.env.DEV_API === "remote";
const API = REMOTE
  ? (process.env.DEV_API_URL || "https://dev-api.myscrollr.com").replace(/\/$/, "")
  : "http://localhost:18080";

function existingKey(...files) {
  for (const f of files) {
    if (!existsSync(p(f))) continue;
    const m = readFileSync(p(f), "utf8").match(/^ENCRYPTION_KEY=(.+)$/m);
    if (m && m[1].trim()) return m[1].trim();
  }
  return null;
}

// ── Templates ────────────────────────────────────────────────────────
const files = (enc, logto) => ({
  "api/.env": `# Generated by \`make setup\`. Safe to edit.
DATABASE_URL=${DB}
REDIS_URL=${REDIS}
PORT=8080
# NOT an address — core only ever uses API_URL as the OIDC \`resource\` it
# requests and the \`aud\` it validates on incoming tokens. Logto issues
# tokens for the resource it has registered, which is the production
# identifier even when you are calling localhost, so pointing this at
# localhost rejects every token with "invalid token audience". Same
# reasoning as VITE_LOGTO_RESOURCE below.
API_URL=https://api.myscrollr.com
FRONTEND_URL=http://localhost:3000
ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5174,tauri://localhost
ENVIRONMENT=development
STRIPE_DISABLED=true
ENCRYPTION_KEY=${enc}
# The /oidc form: core builds its token endpoint as LOGTO_URL + "/token"
# and compares it against the token's \`iss\`. The bare tenant domain 404s
# on token exchange and rejects every token as "invalid token issuer".
LOGTO_URL=${logto.issuer}
LOGTO_JWKS_URL=${logto.jwks}
LOGTO_EXTENSION_APP_ID=${logto.appId}
LOGTO_WEB_APP_ID=${logto.webAppId}
LOGTO_UPLINK_ROLE_ID=
LOGTO_PRO_ROLE_ID=
LOGTO_ULTIMATE_ROLE_ID=
LOGTO_SUPER_USER_ROLE_ID=
`,
  "channels/finance/.env": `DATABASE_URL=${DB}
PORT=3001
ENCRYPTION_KEY=${enc}
# Leave this BLANK. Without a key the finance ingester stays up, skips
# polling, and serves whatever is in Postgres -- and \`make seed\` puts a real
# snapshot there, so you get a populated app with no key at all.
#
# The key that would work here is the PRODUCTION TwelveData key, on a plan
# sized for real users. Pasting it spends their quota to look at your laptop.
TWELVEDATA_API_KEY=
`,
  "channels/sports/.env": `DATABASE_URL=${DB}
PORT=3002
ENCRYPTION_KEY=${enc}
# Leave this BLANK. Same as finance: no key means no polling, and
# \`make seed\` supplies the data instead.
#
# api-sports bills a shared 7,500-requests-per-day budget per sport host,
# split across every league in production. A dev box polling on the
# production key takes that budget from live users.
API_SPORTS_KEY=
`,
  "channels/rss/.env": `DATABASE_URL=${DB}
PORT=3004
ENCRYPTION_KEY=${enc}
`,
  // The marketing site. Stripe price ids are the real test-mode ones from
  // .env.example — they're not secret and the pricing page needs them to
  // render. The publishable key is a placeholder; billing flows won't work
  // until you supply a real pk_test_.
  "myscrollr.com/.env": `VITE_API_URL=${API}
VITE_LOGTO_ENDPOINT=${logto.url}
VITE_LOGTO_APP_ID=${logto.webAppId}
VITE_LOGTO_RESOURCE=https://api.myscrollr.com
VITE_STRIPE_PUBLISHABLE_KEY=pk_test_REPLACE_ME
VITE_STRIPE_PRICE_MONTHLY=price_1TMyBUFk6czwHVgrocQKaBHD
VITE_STRIPE_PRICE_ANNUAL=price_1TMyBUFk6czwHVgr2AysFrfL
VITE_STRIPE_PRICE_PRO_MONTHLY=price_1TMyBUFk6czwHVgrc6YHoQoj
VITE_STRIPE_PRICE_PRO_ANNUAL=price_1TMyBVFk6czwHVgrN2oUq6fx
VITE_STRIPE_PRICE_ULTIMATE_MONTHLY=price_1TMyBVFk6czwHVgriAztoY86
VITE_STRIPE_PRICE_ULTIMATE_ANNUAL=price_1TMyBVFk6czwHVgr9ntOrMXf
VITE_SENTRY_DSN=
SENTRY_ORG=
SENTRY_AUTH_TOKEN=
`,
  "desktop/.env": `# The desktop app talks to ${REMOTE ? "the shared dev API" : "the LOCAL core API"}.
VITE_API_URL=${API}
VITE_AUTH_ENDPOINT=${logto.url}
VITE_LOGTO_APP_ID=${logto.desktopAppId}
# Logto only knows the resources it has registered, so the token is
# requested for the PROD API resource while the app calls the local one.
# Without this, sign-in fails with "resource indicator is missing, or unknown".
VITE_LOGTO_RESOURCE=https://api.myscrollr.com
# Sentry stays off locally.
VITE_SENTRY_DSN=
SENTRY_DSN_RUST=
SENTRY_ORG=
SENTRY_AUTH_TOKEN=
`,
});

// ── Main ─────────────────────────────────────────────────────────────
// Prompt only when there's a human attached. Piped or redirected stdin
// (CI, `yes |`, a script) takes every default instead of hanging forever on
// a question nobody will answer.
const INTERACTIVE = process.stdin.isTTY === true;
const rl = INTERACTIVE
  ? createInterface({ input: process.stdin, output: process.stdout })
  : null;

const ask = async (q, dflt = "") => {
  if (!rl) return dflt;
  const a = (await rl.question(dflt ? `${q} [${dflt}]: ` : `${q}: `)).trim();
  return a || dflt;
};

if (!INTERACTIVE) {
  console.log("setup: no TTY detected - taking every default (no prompts).");
}

console.log(`
  MyScrollr setup
  ---------------
  Generates the .env files for local development.

  Everything below has a working default except the Logto values. You can
  press enter through all of them: the stack will boot and serve public
  data, you just won't be able to sign in until you fill them in.
`);

const enc = existingKey("api/.env") ?? randomBytes(32).toString("hex");

const logto = {
  url: await ask("Logto URL (blank = no auth)", REMOTE ? "https://auth.myscrollr.com" : ""),
  issuer: "",
  jwks: "",
  // Only core reads this (desktop sign-in exchange); a remote setup has no local core.
  appId: REMOTE ? "" : await ask("Logto extension app id", ""),
  // Remote mode talks to the real tenant, whose client ids are public (they
  // ship inside the app bundle and the website), so default them; a blank
  // id is what left web mode unable to sign in on a fresh clone.
  desktopAppId: await ask("Logto DESKTOP app id", REMOTE ? "6y2wqgvkdqmulthvose81" : ""),
  webAppId: await ask("Logto WEBSITE app id", REMOTE ? "4wktntz580tq7y2ve02mo" : ""),
};
// Everything below hangs off the tenant URL — derive rather than ask
// four times. The bare URL is what the Logto SDKs want (they append
// /oidc themselves, so VITE_LOGTO_ENDPOINT and VITE_AUTH_ENDPOINT must
// NOT carry it); core talks to the OIDC endpoints directly and needs the
// /oidc form for both the token endpoint and the `iss` it validates.
{
  const base = logto.url.replace(/\/$/, "");
  logto.url = base;
  logto.issuer = base ? `${base}/oidc` : "";
  logto.jwks = base ? `${base}/oidc/jwks` : "";
}

rl?.close();

console.log("");
let wrote = 0;
for (const [rel, body] of Object.entries(files(enc, logto))) {
  // Remote: front-ends only; api/ and channels/ configure a backend nobody runs.
  if (REMOTE && !/^(desktop|myscrollr\.com)\//.test(rel)) continue;
  const dest = p(rel);
  if (existsSync(dest) && !FORCE) {
    // An explicit DEV_API=remote|local is a request to switch, so the API
    // base of an existing front-end .env is rewritten in place; everything
    // else in the file (Logto, analytics, …) is kept. Without DEV_API the
    // old rule holds: never touch an existing file.
    if (process.env.DEV_API && /^(desktop|myscrollr\.com)\//.test(rel)) {
      const cur = readFileSync(dest, "utf8");
      const next = cur.replace(/^VITE_API_URL=.*$/m, `VITE_API_URL=${API}`);
      if (next !== cur) {
        writeFileSync(dest, next, "utf8");
        console.log(`  point ${rel.padEnd(24)} VITE_API_URL -> ${API}`);
        wrote++;
        continue;
      }
    }
    console.log(`  keep  ${rel.padEnd(24)} exists (--force to overwrite)`);
    continue;
  }
  mkdirSync(path.dirname(dest), { recursive: true });
  writeFileSync(dest, body, "utf8");
  console.log(`  wrote ${rel}`);
  wrote++;
}

if (REMOTE) {
  console.log(`
  ${wrote} file(s) written. Front-ends will call ${API} -- no Docker needed.
  Other settings in existing .env files are kept. Back to local: make setup DEV_API=local

  Next:  make desktop   (or make web)
`);
  process.exit(0);
}

console.log(`
  ${wrote} file(s) written. ENCRYPTION_KEY is shared across all of them --
  core encrypts third-party tokens and the channels decrypt them, so they
  must match.

  Every upstream API key is intentionally blank. Do not paste production keys
  in: \`make seed\` loads a committed snapshot so the app has real data
  without spending the quota that live users depend on.

  Next:  make up  &&  make seed
`);
